version: '3.8'

services:
  sova-tts:
    container_name: sova-tts
    build:
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "8899:8899"
    volumes:
      - .:/sova-tts
    restart: unless-stopped
